name: abstimmung

permissions:
  contents: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: '*/8 * * * *'
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: dpa-query
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install all necessary packages
      run: pip install jupyter pandas requests nbformat
    - name: Format Abstimmung Data
      run: |
        jupyter nbconvert --to notebook --execute "abstimmung.ipynb" --stdout
        jupyter nbconvert --to notebook --execute "leewas.ipynb" --stdout
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push